# /etc/docker/compose/kafka-manager/docker-compose.yml
# version: '3.6'
services:
  kafka_manager:
    image: hlebalbau/kafka-manager:latest
    ports:
      - "8000:8000"
    environment:
      ZK_HOSTS: "172.31.9.21:2181"
      APPLICATION_SECRET: "random-secret"
    command: -Dpidfile.path=/dev/null